# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    # "last stable CPython version":
    python: "3"

sphinx:
  configuration: docs/conf.py
  builder: dirhtml

# Additional formats to build:
formats: all

python:
  install:
    - requirements: docs/requirements.txt
